### ISSUE TITLE
Improve Azure File Share support

### ISSUE THREAD

**Issue by vrepetskyi** [JonasAlfredsson/docker-nginx-certbot#218]
Hi, @JonasAlfredsson. First of all, thank you for your work. This repository helped me automate certificate creation.

While deploying to Azure with docker-compose I encountered the following problem:
- To mount a volume and persist already generated keys in Azure, you need a Storage Account -> File Share (an alternative to AWS S3). You declare it like that:
```
volumes:
  secrets:
    driver: azure_file
    driver_opts:
      share_name: secrets
      storage_account_name: xxx
```
- When I mount it (`- secrets:/etc/letsencrypt`) and start the container, I get the following error:
```
Requesting a certificate for <domain>
Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certbot/_internal/main.py", line 1873, in main
    return config.func(config, plugins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certbot/_internal/main.py", line 1600, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certbot/_internal/main.py", line 143, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certbot/_internal/client.py", line 528, in obtain_and_enroll_certificate
    return storage.RenewableCert.new_lineage(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certbot/_internal/storage.py", line 1099, in new_lineage
    os.symlink(_relpath_from_file(archive_target[kind], target[kind]), target[kind])
OSError: [Errno 95] Operation not supported: '../../archive/<domain>.dns-route53-0001/cert1.pem' -> '/etc/letsencrypt/live/<domain>.dns-route53-0001/cert.pem'
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
2023/12/03 16:35:14 [error] Certbot failed for '<domain>.dns-route53'. Check the logs for details.
```
- Based on the traceback, I assume that Azure File Share doesn't support symlinks
- If I don't mount the volume, the whole process goes normally 

My naive solution to that is the following:
- Copy contents of the volume to `/etc/letsencrypt` on container start
- Copy contents of `/etc/letsencrypt` to the volume when there is a change

In such a way, it is still possible to persist the keys, and no symlinks to Azure File Share are created by certbot.

Thanks!

**Comment by vrepetskyi** [comment]
Thank you for your fast response.

Here's [the solution](https://github.com/BbqGamer/building-plot-search/tree/5698fa48dffb79b5a70510418c9a809d92265e8b/backend/bps-backend) I came up with in the meantime. Because the container's IP address is assigned upon its creation, I automated the DNS record update as well. My scripts deploy FastAPI to Azure, point Route 53 to it, and start your service next. The keys are successfully stored on a separate File Share volume.

The solution isn't perfect, but someone may find it helpful.
