### ISSUE TITLE
Failed Certificate renewal process

### ISSUE THREAD

**Issue by Stathogon** [JonasAlfredsson/docker-nginx-certbot#72]
Hello there,
im trying to get the docker container up and running but i get the attached error message.
The error message tells me that the docker container has problems resolving the names (Temporary failure in name resolution).
But i checked my DNS-Server and the Container doesnt request any dns resolving. Has someone the same problem or am i doing something wrong? I followed the given Documentation and the server is reachable through port 80 and 443.
```
Requesting an RSA certificate for 'pb.jn-it.de'
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7faf8ff319b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7faf8ff319b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/main.py", line 1566, in main
    return config.func(config, plugins)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/main.py", line 1408, in certonly
    le_client = _init_le_client(config, auth, installer)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/main.py", line 756, in _init_le_client
    acc, acme = _determine_account(config)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/main.py", line 674, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/client.py", line 182, in register
    acme = acme_from_config_key(config, key)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/client.py", line 46, in acme_from_config_key
    client = acme_client.BackwardsCompatibleClientV2(net, key, config.server)
  File "/usr/local/lib/python3.7/dist-packages/acme/client.py", line 835, in __init__
    directory = messages.Directory.from_json(net.get(server).json())
  File "/usr/local/lib/python3.7/dist-packages/acme/client.py", line 1179, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/usr/local/lib/python3.7/dist-packages/acme/client.py", line 1128, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7faf8ff319b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
Certbot failed for 'pb.jn-it.de'. Check the logs for details.
Requesting an RSA certificate for 'asterior.de'
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fa4f0395c88>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4f0395c88>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/main.py", line 1566, in main
    return config.func(config, plugins)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/main.py", line 1408, in certonly
    le_client = _init_le_client(config, auth, installer)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/main.py", line 756, in _init_le_client
    acc, acme = _determine_account(config)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/main.py", line 674, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/client.py", line 182, in register
    acme = acme_from_config_key(config, key)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/client.py", line 46, in acme_from_config_key
    client = acme_client.BackwardsCompatibleClientV2(net, key, config.server)
  File "/usr/local/lib/python3.7/dist-packages/acme/client.py", line 835, in __init__
    directory = messages.Directory.from_json(net.get(server).json())
  File "/usr/local/lib/python3.7/dist-packages/acme/client.py", line 1179, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/usr/local/lib/python3.7/dist-packages/acme/client.py", line 1128, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4f0395c88>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
Certbot failed for 'asterior.de'. Check the logs for details.
Could not find keyfile file '/etc/letsencrypt/live/pb.jn-it.de/privkey.pem' in '/etc/nginx/conf.d/Reverse-Proxy.conf.nokey'
Could not find keyfile file '/etc/letsencrypt/live/asterior.de/privkey.pem' in '/etc/nginx/conf.d/Reverse-Proxy.conf.nokey'
Could not find fullchain file '/etc/letsencrypt/live/pb.jn-it.de/fullchain.pem' in '/etc/nginx/conf.d/Reverse-Proxy.conf.nokey'
Could not find fullchain file '/etc/letsencrypt/live/asterior.de/fullchain.pem' in '/etc/nginx/conf.d/Reverse-Proxy.conf.nokey'
Could not find chain file '/etc/letsencrypt/live/pb.jn-it.de/chain.pem' in '/etc/nginx/conf.d/Reverse-Proxy.conf.nokey'
Could not find chain file '/etc/letsencrypt/live/asterior.de/chain.pem' in '/etc/nginx/conf.d/Reverse-Proxy.conf.nokey'
2021/08/29 15:57:51 [notice] 292#292: signal process started
2021/08/29 15:57:51 [notice] 120#120: signal 1 (SIGHUP) received from 292, reconfiguring
2021/08/29 15:57:51 [notice] 120#120: reconfiguring
Autorenewal service will now sleep 8d
```

**Comment by JonasAlfredsson** [comment]
Hi  Stathogon,

Certbot will try to connect to the Let's Encrypt servers in order to request certificates, the exact URL can be found in the same message that says it fails too look it up:

```
... HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443) ..... [Errno -3] Temporary failure in name resolution
```

There can be a lot of reasons to why the name resolution fails;
- No internet connection
- Wrongly configured network for the container
- VPN or similar DNS redirection that conflicts with Docker's own DNS
- Error in the upstream DNS server
- Bug in certbot's code

Since it sounds like you do some custom DNS server routing I would probably try to "jump into" the offending container and run `dig` to try to see if you can better understand where the request is going. In the following example I explicitly tell it to use an OpenDNS server to look up the name.

```
dig @208.67.222.222 acme-v02.api.letsencrypt.org

;; ANSWER SECTION:
acme-v02.api.letsencrypt.org. 1912 IN	CNAME	prod.api.letsencrypt.org.
prod.api.letsencrypt.org. 156	IN	CNAME	ca80a1adb12a4fbdac5ffcbc944e9a61.pacloudflare.com.
ca80a1adb12a4fbdac5ffcbc944e9a61.pacloudflare.com. 141 IN A 172.65.32.248
```

**Comment by Stathogon** [comment]
Thanks for the quick response.
It kinda helped. After i used dig it worked. And after i used the "/scripts/run_certbot.sh force" it got the certificates without a Problem. But when i restart the container the same error occurs. And now i´ve got trouble setting up a reverse proxy setup.
I use now this .conf file in the user_conf.d directory:
```
server {
    # Listen to port 443 on both IPv4 and IPv6.
    listen 443 ssl default_server reuseport;

    # Domain names this server should respond to.
    server_name pb.jn-it.de;

    # Load the certificate files.
    ssl_certificate         /etc/letsencrypt/live/pb.jn-it.de/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/pb.jn-it.de/privkey.pem;

    # Load the Diffie-Hellman parameter.
    ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;

    # Define the ciphers to use in the preferred order.
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:DHE+AESGCM:DHE:!RSA!aNULL:!eNULL:!LOW:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!CAMELLIA:!SEED";

    location / {
        proxy_pass https://192.168.188.50:443;
    }
}
server {
    # Listen to port 443 on both IPv4 and IPv6.
    listen 443 ssl reuseport;

    # Domain names this server should respond to.
    server_name asterior.de;

    # Load the certificate files.
    ssl_certificate         /etc/letsencrypt/live/asterior.de/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/asterior.de/privkey.pem;

    # Load the Diffie-Hellman parameter.
    ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;

    # Define the ciphers to use in the preferred order.
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:DHE+AESGCM:DHE:!RSA!aNULL:!eNULL:!LOW:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!CAMELLIA:!SEED";

    location / {
        proxy_pass https://192.168.188.51:443;
    }
}

```
But it says the following error-message:

```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
Starting the Nginx service
Starting the autorenewal service
2021/08/30 16:18:07 [emerg] 95#95: duplicate listen options for 0.0.0.0:443 in /etc/nginx/conf.d/Reverse-Proxy.conf:26
nginx: [emerg] duplicate listen options for 0.0.0.0:443 in /etc/nginx/conf.d/Reverse-Proxy.conf:26
```
Yes the Error-message speaks for itself. but how am i supposed to configure something like a reverse-proxy if im not able to use a port more then 1 time?

**Comment by JonasAlfredsson** [comment]
Hmmm, I found [this post](url) that said something about `reuseport` can only be defined once, and it will then apply to all the others. Otherwise I think you are doing stuff correctly. 

Try removing it so it is only defined once, and write here if you still have trouble :)

**Comment by Stathogon** [comment]
Thanks a lot, that was my mistake. Im still getting the inital error but that could be something with my own setup. Big thanks.
Maybe you could add a second server on the examples site to make that clear?

**Comment by JonasAlfredsson** [comment]
Excellent. 
The first error is more difficult for me to helt you with, especially since you have a custom DNS setup. If you start another container (just Ubuntu or similar) do you have the same problem from within those?

**Comment by Stathogon** [comment]
So interesting phenomenon if i restart the container i get the error above. but if i use the "/scripts/run_certbot.sh force" it works fine and i see the dns request in my dns-server. Could it be something like the network is not up, the script runs, couldnt get a connection. Then the network / resolv service comes up and i run the script afterwards. Otherwise i cant quit explain to me where the error is. Also the autorenewal works without a problem.

**Comment by JonasAlfredsson** [comment]
I have not experienced this issue before, and I suspect it has something to do with your more exotic DNS setup. 
If there is only some waiting necessary you can perhaps add a simple `sleep` script to the entrpypoint.d/ folder?
