### ISSUE TITLE
I get the error: "Please enter the domain name(s) you would like on your certificate (comma and/or space separated)"

### ISSUE THREAD

**Issue by kovan** [JonasAlfredsson/docker-nginx-certbot#76]
Hi. 
I am trying to set up this, but I am not sure that I am doing it right.
I have changed the domains to my own ones in example NGINX conf file, and I have copied the file to user_conf.d
Then I have started the container with docker-compose up, but it fails: 

```
nginx_1  | certbot.errors.MissingCommandlineFlag: Missing command line flag or config entry for this setting:
nginx_1  | Please enter the domain name(s) you would like on your certificate (comma and/or space separated)

```
Here is the full output:
```

nginx_1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx_1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/                                                                                                                      nginx_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx_1  | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
nginx_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx_1  | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx_1  | Creating symlink '/etc/nginx/conf.d/example_server.conf' to '/etc/nginx/user_conf.d/example_server.conf'
nginx_1  | Could not find keyfile file '/etc/letsencrypt/live/test-name/privkey.pem' in '/etc/nginx/conf.d/example_server.conf'
nginx_1  | Could not find fullchain file '/etc/letsencrypt/live/test-name/fullchain.pem' in '/etc/nginx/conf.d/example_server.conf'
nginx_1  | Could not find chain file '/etc/letsencrypt/live/test-name/chain.pem' in '/etc/nginx/conf.d/example_server.conf'
nginx_1  | Could not find dhparam file '/etc/letsencrypt/dhparams/dhparam.pem' in '/etc/nginx/conf.d/example_server.conf'
nginx_1  | Important file(s) for '/etc/nginx/conf.d/example_server.conf' are missing, disabling...
nginx_1  | Starting the Nginx service
nginx_1  | Starting the autorenewal service
nginx_1  | 2021/09/25 21:27:40 [notice] 116#116: using the "epoll" event method
nginx_1  | 2021/09/25 21:27:40 [notice] 116#116: nginx/1.21.0
nginx_1  | 2021/09/25 21:27:40 [notice] 116#116: built by gcc 8.3.0 (Debian 8.3.0-6)
nginx_1  | 2021/09/25 21:27:40 [notice] 116#116: OS: Linux 5.10.60-v7+
nginx_1  | 2021/09/25 21:27:40 [notice] 116#116: getrlimit(RLIMIT_NOFILE): 1048576:1048576
nginx_1  | 2021/09/25 21:27:40 [notice] 116#116: start worker processes
nginx_1  | 2021/09/25 21:27:40 [notice] 116#116: start worker process 126
nginx_1  | 2021/09/25 21:27:40 [notice] 116#116: start worker process 128
nginx_1  | 2021/09/25 21:27:40 [notice] 116#116: start worker process 129
nginx_1  | 2021/09/25 21:27:40 [notice] 116#116: start worker process 130
nginx_1  | Couldn't find the dhparam file '/etc/letsencrypt/dhparams/dhparam.pem'; creating it...
nginx_1  | mkdir: created directory '/etc/letsencrypt/dhparams'
nginx_1  |
nginx_1  |     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
nginx_1  |     %                        ATTENTION!                       %
nginx_1  |     %                                                         %
nginx_1  |     % This script will now create a 2048 bit Diffie-Hellman   %
nginx_1  |     % parameter to use during the SSL handshake.              %
nginx_1  |     %                                                         %
nginx_1  |     % >>>>>      This MIGHT take a VERY long time!      <<<<< %
nginx_1  |     %    (Took 65 minutes for 4096 bit on an old 3GHz CPU)    %
nginx_1  |     %    (Took 65 minutes for 4096 bit on an old 3GHz CPU)    %
nginx_1  |     %                                                         %
nginx_1  |     % However, there is some randomness involved so it might  %
nginx_1  |     % be both faster or slower for you. 2048 is secure enough %
nginx_1  |     % for today and quite fast to generate. These files will  %
nginx_1  |     % only have to be created once so please be patient.      %
nginx_1  |     % A message will be displayed when this process finishes. %
nginx_1  |     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
nginx_1  |
nginx_1  | Will now output to the following file: '/etc/letsencrypt/dhparams/dhparam.pem'
nginx_1  | Generating DH parameters, 2048 bit long safe prime, generator 2
nginx_1  | This is going to take a long time
nginx_1  | ...........................................................................................................................................................................................................................................+.................................................................................................................................................................................................................................+....................+..............+............................................................................................................................+...................+........................................................................................................................................................................................................................................+............................+..................+...........+.................................+..................................++*++*++*++*
nginx_1  |
nginx_1  |     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
nginx_1  |     % >>>>>   Diffie-Hellman parameter creation done!   <<<<< %
nginx_1  |     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
nginx_1  |
nginx_1  | Starting certificate renewal process
nginx_1  | Requesting an RSA certificate for 'test-name'
nginx_1  | Account registered.
nginx_1  | Saving debug log to /var/log/letsencrypt/letsencrypt.log
nginx_1  | Exiting abnormally:
nginx_1  | Traceback (most recent call last):
nginx_1  |   File "/usr/local/bin/certbot", line 8, in <module>
nginx_1  |     sys.exit(main())
nginx_1  |   File "/usr/local/lib/python3.7/dist-packages/certbot/main.py", line 15, in main
nginx_1  |     return internal_main.main(cli_args)
nginx_1  |   File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/main.py", line 1566, in main
nginx_1  |     return config.func(config, plugins)
nginx_1  |   File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/main.py", line 1418, in certonly
nginx_1  |     domains, certname = _find_domains_or_certname(config, installer)
nginx_1  |   File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/main.py", line 458, in _find_domains_or_certname
nginx_1  |     domains = display_ops.choose_names(installer, question)
nginx_1  |   File "/usr/local/lib/python3.7/dist-packages/certbot/display/ops.py", line 113, in choose_names
nginx_1  |     return _choose_names_manually()
nginx_1  |   File "/usr/local/lib/python3.7/dist-packages/certbot/display/ops.py", line 190, in _choose_names_manually
nginx_1  |     cli_flag="--domains", force_interactive=True)
nginx_1  |   File "/usr/local/lib/python3.7/dist-packages/certbot/display/util.py", line 121, in input_text
nginx_1  |     force_interactive=force_interactive)
nginx_1  |   File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/display/obj.py", line 466, in input
nginx_1  |     self._interaction_fail(message, cli_flag)
nginx_1  |   File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/display/obj.py", line 405, in _interaction_fail
nginx_1  |     raise errors.MissingCommandlineFlag(msg)
nginx_1  | certbot.errors.MissingCommandlineFlag: Missing command line flag or config entry for this setting:
nginx_1  | Please enter the domain name(s) you would like on your certificate (comma and/or space separated)
nginx_1  |
nginx_1  | (You can set this with the --domains flag)
nginx_1  | Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
nginx_1  | Certbot failed for 'test-name'. Check the logs for details.
nginx_1  | Could not find keyfile file '/etc/letsencrypt/live/test-name/privkey.pem' in '/etc/nginx/conf.d/example_server.conf.nokey'
nginx_1  | Could not find fullchain file '/etc/letsencrypt/live/test-name/fullchain.pem' in '/etc/nginx/conf.d/example_server.conf.nokey'
nginx_1  | Could not find chain file '/etc/letsencrypt/live/test-name/chain.pem' in '/etc/nginx/conf.d/example_server.conf.nokey'
nginx_1  | 2021/09/25 21:30:22 [notice] 260#260: signal process started
nginx_1  | 2021/09/25 21:30:22 [notice] 116#116: signal 1 (SIGHUP) received from 260, reconfiguring
nginx_1  | 2021/09/25 21:30:22 [notice] 116#116: reconfiguring
nginx_1  | Autorenewal service will now sleep 8d
nginx_1  | 2021/09/25 21:30:22 [notice] 116#116: using the "epoll" event method
nginx_1  | 2021/09/25 21:30:22 [notice] 116#116: start worker processes
nginx_1  | 2021/09/25 21:30:22 [notice] 116#116: start worker process 261
nginx_1  | 2021/09/25 21:30:22 [notice] 116#116: start worker process 262
nginx_1  | 2021/09/25 21:30:22 [notice] 116#116: start worker process 263
nginx_1  | 2021/09/25 21:30:22 [notice] 116#116: start worker process 264
nginx_1  | 2021/09/25 21:30:22 [notice] 126#126: gracefully shutting down
nginx_1  | 2021/09/25 21:30:22 [notice] 128#128: gracefully shutting down
nginx_1  | 2021/09/25 21:30:22 [notice] 129#129: gracefully shutting down
nginx_1  | 2021/09/25 21:30:22 [notice] 128#128: exiting
nginx_1  | 2021/09/25 21:30:22 [notice] 130#130: gracefully shutting down
nginx_1  | 2021/09/25 21:30:22 [notice] 130#130: exiting
nginx_1  | 2021/09/25 21:30:22 [notice] 128#128: exit
nginx_1  | 2021/09/25 21:30:22 [notice] 126#126: exiting
nginx_1  | 2021/09/25 21:30:22 [notice] 126#126: exit
nginx_1  | 2021/09/25 21:30:22 [notice] 130#130: exit
nginx_1  | 2021/09/25 21:30:22 [notice] 116#116: signal 17 (SIGCHLD) received from 128
nginx_1  | 2021/09/25 21:30:22 [notice] 116#116: worker process 128 exited with code 0
nginx_1  | 2021/09/25 21:30:22 [notice] 116#116: signal 29 (SIGIO) received
nginx_1  | 2021/09/25 21:30:22 [notice] 116#116: signal 17 (SIGCHLD) received from 126
nginx_1  | 2021/09/25 21:30:22 [notice] 116#116: worker process 126 exited with code 0
nginx_1  | 2021/09/25 21:30:22 [notice] 116#116: worker process 130 exited with code 0
nginx_1  | 2021/09/25 21:30:22 [notice] 116#116: signal 29 (SIGIO) received
nginx_1  | 2021/09/25 21:30:22 [notice] 116#116: signal 17 (SIGCHLD) received from 130
nginx_1  | 2021/09/25 21:30:30 [notice] 129#129: exiting
nginx_1  | 2021/09/25 21:30:30 [notice] 129#129: exit
nginx_1  | 2021/09/25 21:30:30 [notice] 116#116: signal 17 (SIGCHLD) received from 129
nginx_1  | 2021/09/25 21:30:30 [notice] 116#116: worker process 129 exited with code 0
nginx_1  | 2021/09/25 21:30:30 [notice] 116#116: signal 29 (SIGIO) received
```

Am I missing something?, what is the problem here?
Thank you for your time.

**Comment by kovan** [comment]
OK a semicolon was missing at the end of a line in the NGINX config file.

**Comment by JonasAlfredsson** [comment]
Glad to hear that you found the issue, just open a new issue if you run into anything else :)
